version: '3'
services:
  webdav:
    image: derkades/webdav
    restart: unless-stopped
    environment:
      USERNAME: testing
      PASSWORD: testing123
    volumes:
      - ./dav:/data
    ports:
      - 1180:80
  pix:
    build:
      dockerfile: Dockerfile
    image: ghcr.io/brumhard/pix:v0.2.0
    restart: unless-stopped
    volumes:
      - ./dav:/data
    command:
      - -images
      - /data
    ports:
      - 8888:8888
