version: '3'
services:
  webdav:
    image: bytemark/webdav
    restart: unless-stopped
    environment:
      AUTH_TYPE: Basic
      USERNAME: testing
      PASSWORD: testing123
    volumes:
      - ./dav:/var/lib/dav
    ports:
      - 1280:80
  ogframe:
    build:
      dockerfile: Dockerfile
    image: github.com/brumhard/ogframe-server
    restart: unless-stopped
    volumes:
      - ./dav:/var/lib/dav
    command:
      - -images
      - /var/lib/dav/data
    ports:
      - 8080:8080
