version: '3'
services:
  pix:
    build:
      dockerfile: Dockerfile
    image: ghcr.io/brumhard/pix:v0.3.0
    restart: unless-stopped
    volumes:
      - ./dav:/data
    command:
      - -images
      - /data
    ports:
      - 8420:8420
